### ISSUE TITLE
"Headers are immutable" Error when implementing oAuth2

### ISSUE THREAD

**Issue by trchristensen** [xstevenyung/fresh-session#10]
Hey Steven, just want to thank you for making this. Works perfectly on my new portfolio site. I'm sure you're busy but was hoping you could help me with a noob issue.

I'm getting a Typescript "Headers are immutable." error when using a "deno_grant" library for oauth2.

Basically when the client is redirecting the user to another site (https://discord.com/api/oauth2/authorize...), I'm getting this error. 

I am still trying to wrap my head around the cookie session flow. Anyway, appreciate it!

**Comment by excessivecoding** [comment]
Hey there, I've got this issue a couple of time. If i had to guess, I think you are using `Response.redirect`, which make the headers immutable like the error says (don't really know why)

We need to handle this issue at some point. But as a workaround, you can use:

```ts
new Response(null, {
	status: 302,
	headers: {
		Location: "your-url"
	}
})
```

This will redirect like usual but allow for fresh-session to make headers modifications

Don't hesitate to ask if you have any question regarding OAuth2 or other things, always happy to help

**Comment by trchristensen** [comment]
NIce! Ya you're right, I was using Response.redirect. Your workaround fixed the issue though. Thanks! I really appreciate you helping me and I might take you up on that offer. There aren't a whole lot of resources on Deno Fresh or even Deno for that matter. Have a good one!

**Comment by excessivecoding** [comment]
If you (or anyone passing by) have time, I would love a PR that add a "Caveats" / "FAQ" in the readme which answer this question for future reference !

Or better a fix for the issue itself if you are up for it

Reopening the issue so we can track this
