### ISSUE TITLE
Regist letest version(0.1.9) to deno.land/x

### ISSUE THREAD

**Issue by Octo8080X** [xstevenyung/fresh-session#12]
Hello @xstevenyung san.

The latest version on github and the latest version on deno.land/x seem to be out of sync.

I think the next one will be 0.1.9, can I tag it?

**Comment by excessivecoding** [comment]
Sorry for the delay, I completely forgot to do it.

I just tagged 0.2.0

**Comment by Octo8080X** [comment]
@xstevenyung 
Thank you. It helped me a lot.
