### ISSUE TITLE
Pinned `fresh@1.0.1` version causing some problems when running `deno cache`

### ISSUE THREAD

**Issue by hugopeixoto** [xstevenyung/fresh-session#16]
I'm using `fresh-session` with `fresh@1.1.3`, and I ran into an issue when running `deno cache`:

```
error: pragma cannot be set when runtime is automatic at https://deno.land/x/fresh@1.0.1/src/server/default_error_page.tsx:1:1
The command '/bin/sh -c deno cache main.ts --import-map=import_map.json' returned a non-zero code: 1
```

Fresh [supports JSX automatic mode from `1.1.0`](https://github.com/denoland/fresh/commit/b12867a5823a338b318b14f1b6e399e61064dce9), so this shouldn't be a problem. Unfortunately `fresh-session` depends on `fresh@1.0.1`:

```ts
# src/deps.ts:
export type { MiddlewareHandlerContext } from "https://deno.land/x/fresh@1.0.1/server.ts";
```

I worked around this by adding the following entry in `import_maps.json`:

```json
{
  "imports": {
    ...,
    "https://deno.land/x/fresh@1.0.1/": "https://deno.land/x/fresh@1.1.3/"
  }
}
```

While this workaround works, should this be addressed by fresh-session by, for example, bumping the dependency?

**Comment by Octo8080X** [comment]
@hugopeixoto 

I am trying to solve the situation.
But I am unable to reproduce the same phenomenon.
Can you tell me more about the situation?

I have confirmed that fresh@1.1.4 and fresh-session@0.2.0 work.

**Comment by sylc** [comment]
I'm having the same issue. `deno run` is working fine but doing `deno cache --reload ./main.ts` will trigger the error.
