### ISSUE TITLE
add support for user-land session implementation

### ISSUE THREAD

**Issue by excessivecoding** [xstevenyung/fresh-session#2]
At the moment, Fresh Session only support cookie session based on JWT and Redis (thanks to @Octo8080X ).

Remix provide a nice way to create session storage that we can take inspiration from https://remix.run/docs/en/v1/api/remix#createsessionstorage

After implementing this, we should rewrite all existing adapter to use our new function

**Comment by Octo8080X** [comment]
Hello.

I made a Redis store.
Please take a look if you like.

[Add Redis session store.](https://github.com/xstevenyung/fresh-session/pull/3)

**Comment by digitaldesigndj** [comment]
@Octo8080X Same thing here! I built a redis store, mine has some logging stuff borrowed from oak there too.

https://gist.github.com/digitaldesigndj/73daa4222ff685f77a1a0e84f3583cc4

**Comment by excessivecoding** [comment]
Thanks a lot @Octo8080X for the initial work, I will look at it next week as I'm on holiday at the moment !

**Comment by Octo8080X** [comment]
The redis session has been developed. This issue is closed. This issue is now closed.
