### ISSUE TITLE
0.2.1 examples broken due to missing WithSession

### ISSUE THREAD

**Issue by daniel-bytes** [xstevenyung/fresh-session#27]
The example documentation in README.md does not work as the `WithSession` type has been removed.  Reverting to 0.2.0 fixes the example code, as well as re-implementing `WithSession` at the time of usage in the middleware and any handlers.  It's not clear to me if removing this was a mistake or the docs should just be updated.  

I do see the type exists in a new interface.ts file, perhaps it just needs to be exported from mod.ts?

Instead of opening an issue I initially tried to open a PR with an updated README but I'm receiving permission denied pushing a new branch.

**Comment by zbynekwinkler** [comment]
There is a fix already
- #22 

But it is not released yet
- #28

**Comment by Octo8080X** [comment]
@daniel-bytes san @zwn san

Our apologies.
Thanks for letting us know.
Please give us a little time as we will have a new release out today or tomorrow.

Thank you.

**Comment by Octo8080X** [comment]
@daniel-bytes san @zwn san 

New release. The problem should be resolved, so please give it a try.
Thank you very much.
