### ISSUE TITLE
Can we have a new release?

### ISSUE THREAD

**Issue by zbynekwinkler** [xstevenyung/fresh-session#28]
Can we have 0.2.2 to include this fix:
- #22

I am trying fresh 1.3.0 and typescript complains since I import stuff from 1.3.0 but fresh-session 0.2.0 imports from 1.0.1:

![image](https://github.com/Octo8080X/fresh-session/assets/1130051/14b7f749-33c3-484c-a234-8e6247d0aade)

So if fresh could be updated as well that would be great.

**Comment by digitaldesigndj** [comment]
If you can't wait, you can import the current branch from Github like this:
```(ts)
  "imports": {
    "fresh-session/": "https://raw.githubusercontent.com/Octo8080X/fresh-session/main/"
  },
```

**Comment by Octo8080X** [comment]
@digitaldesigndj 

New release. The problem should be resolved, so please give it a try.
Thank you very much.

**Comment by zbynekwinkler** [comment]
Thanks 👍
