### ISSUE TITLE
We didn't detect a env variable `APP_KEY` (fresh 1.4.3)

### ISSUE THREAD

**Issue by sizoroot** [xstevenyung/fresh-session#32]
In the latest version of fresh (1.4.3) it does not detect the APP_KEY variable in the .env file.

[FRESH SESSION] Warning: We didn't detect a env variable `APP_KEY`, if you are in production please fix this ASAP to avoid any security issue.

**Comment by Octo8080X** [comment]
@ovniroto 

Thanks for letting me know. Appreciate it.

fresh-session was not originally designed to automatically load .env files.
We also do not expect Fresh to read .env files.

Therefore, there are three options that can be taken. 

1. inline
```sh
APP_KEY=hoge deno task start
```

2. system environment variables
```sh
export APP_KEY=hoge
deno task start
```

3. dev.ts 
```ts
#!/usr/bin/env -S deno run -A --watch=static/,routes/

import "https://deno.land/std@0.202.0/dotenv/load.ts"; // << Add.

import dev from "$fresh/dev.ts";

await dev(import.meta.url, "./main.ts");
```

We believe these are the best ways to address this issue.

**Comment by Octo8080X** [comment]
@ovniroto

If there is no problem with this method of response, please let us know so we can close this issue.
(Due date 10/1/2023)

**Comment by sizoroot** [comment]
It has worked, thank you very much.
