### ISSUE TITLE
Possibility to reduce learning curve?

### ISSUE THREAD

**Issue by vicary** [xstevenyung/fresh-session#39]
Since Deno itself already supports WebCrypto, is it possible to drop iron_webcrypto? 

Deno Fresh itself lacks many essentials such as auth, new users may be relunctant to understand yet another repo just to use fresh-session.

**Comment by Octo8080X** [comment]
Thanks @vicary san, for your input.

> Deno Fresh itself lacks many essentials such as auth

This is one of the many things I agree with.
We want to make sure that we have the right features to serve as a foundation.

In the very immediate future, we are not considering removing iron-webcrypto.
The same goes for the new version we are preparing now.
I do not intend to get into implementations that directly use WebCrypto by ourselves now.
I think that not using WebCrypto on its own makes it easier to understand as a stand-alone constant session module.

If a replacement for iron-webcrypto can be provided, I think it is well worth considering.

(Sorry for the delay in responding to you.)

**Comment by vicary** [comment]
Hey, thanks for the response.

It may take more time for me to understand iron_webcrypto enough to put my new app together, but I think its fair to keep whatever considerations that brings the repo forward.

Please keep on the good works, hope all of you have a nice day!
