### ISSUE TITLE
Add documentation for Redis Store with example

### ISSUE THREAD

**Issue by excessivecoding** [xstevenyung/fresh-session#6]
Thanks to @Octo8080X work, we now have access to a Redis store for session.

We need to add some documentation (inspiration can be taken from the PR https://github.com/xstevenyung/fresh-session/pull/3) to help people understand how to work with it.

**Comment by Octo8080X** [comment]
Thanks to @xstevenyung.
I'll add the one I incorporated as an example, but what do you think?

**Comment by excessivecoding** [comment]
The one in your PR would be a great start to the documentation!
